### ISSUE TITLE
Consider same schema for Planet and Planet History

### ISSUE THREAD

**Issue by fosskers** [mojodna/osm2orc#7]
Currently, the two schemas are nearly identical except for `visible` which is included in History. I had confirmed with @mojodna a while ago that everything in Planet is implicitly visible, and so the field wasn't included. However, making that field explicit in Planet as well would allow for nice code re-use in tools that wish to read from both tables.

Thoughts?

**Comment by sethfitz** [comment]
I'd considered this too early on. It may be too late to change this, unless appending a column is supported without interfering with already-registered schemas.

If that works, I'm all for it.

**Comment by fosskers** [comment]
It's never too late! Older tools that read Planet assuming no `visible` field wouldn't be punished by its addition, since `SELECT` has that predictable behaviour.

**Comment by sethfitz** [comment]
Confirmed that duplicating the `planet_history` external table schema without `visible` works.

Let's do it.

**Comment by fosskers** [comment]
> Confirmed that duplicating the planet_history external table schema without visible works.

Sorry I'm a bit confused by this. `Let's do it` == `Let's add visible to Planet`?

**Comment by sethfitz** [comment]
Yes!

**Comment by fosskers** [comment]
Yay! You don't know how much boilerplate you just killed heh
